import math
mytup= (8,'good','soccer', 37.5,'player',9,)
mytup2= ('beginner', 7,'car', 44, 'driver',12)
mytup3= (4, 5, 0, 9)
mytup4= ('a','ab','c','cc')
mytup5= (4, 5, 70, 9)
mytup6= ('a','ab','c','cc','kk')
mytup7=(99,)
print(mytup7)
print (mytup[1:3])
print (mytup2[2:])
print (len(mytup))
print (mytup + mytup2)
print (mytup * 3)
print ('good' in mytup)
print (max (mytup3))
print (min (mytup4))
print (sorted(mytup4))
d = (mytup3== mytup5)
#print ((mytup3 > mytup4))# error incompatible data type
print (d)
print ((mytup4 == mytup6))
#print ((mytup4 < mytup6))
